question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {
        "text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
                "you are free to take it home to eat.",
        "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from the moon.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Gumbo is a stew that originated in Louisiana.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "French is an official language in Canada.", "answer": "True",
                                      "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Nutella is produced by the German company Ferrero.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Bulls are attracted to the color red.", "answer": "False",
                                      "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "The Sun rises from the North.", "answer": "False",
                                      "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "The color orange is named after the fruit.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "You can legally drink alcohol while driving in Mississippi.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Pluto is a planet.", "answer": "False",
                                      "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Adolf Hitler was born in Australia. ", "answer": "False",
                                      "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "When you cry in space, your tears stick to your face.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "The Lego Group was founded in 1932.", "answer": "True",
                                      "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Scotland voted to become an independent country during the referendum from September 2014.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "The National Animal of Scotland is the Unicorn.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "A pasodoble is a type of Italian pasta sauce.",
                                      "answer": "False", "inanswers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Slovakia is a member of European Union-", "answer": "True",
                                      "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "The mitochondria is the powerhouse of the cell.",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Jingle Bells was originally meant for Thanksgiving",
                                      "answer": "True", "inanswers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "text": "Ping-Pong originated in England", "answer": "True",
                                      "inanswers": ["False"]}

]
